# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerreviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='number_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='research',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='affiliation',
            field=models.TextField(null=True),
        ),
    ]
